name: First Workflow
on: workflow_call
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Good bye
        run: echo "Bye Bye"
